### ISSUE TITLE
Commandline Option & Initial Seed Sets

### ISSUE THREAD

**Issue by Hustcw** [sleicasper/aflturbo#1]
Nice work! I want to reproduce the unique path exploration experiments in your paper. (Figure 6) Could you please open source your command-line option like `readelf -a` and the initial seedsets?

**Comment by sleicasper** [comment]
You can get command-line options from the published paper. I can only open source a small part of the initial seeds because some of the data are deleted by accident.

**Comment by sleicasper** [comment]
initial seeds are uploaded. You can check it now :)

**Comment by Hustcw** [comment]
cheers!
